config/routes.rb
Rails.application.routes.draw do

  root :to => 'room_tasks#new'

  resources :room_tasks

  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :users

  patch '/users/', to: 'users#role'

  resources :user_sessions

  get 'login' => 'user_sessions#new', :as => :login

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/room.rb
class Room < ActiveRecord::Base

  has_many :room_tasks
  has_many :tasks, through: :room_tasks, autosave: true
  has_many :users, through: :room_tasks, autosave: true

end

app/models/room_task.rb
class RoomTask < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
  belongs_to :room
end

app/models/task.rb
class Task < ActiveRecord::Base

  has_many :room_tasks
  has_many :users, through: :room_tasks, autosave: true
  has_many :rooms, through: :room_tasks, autosave: true

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  belongs_to :role
  has_many :room_tasks
  has_many :tasks, through: :room_tasks, autosave: true
  has_many :rooms, through: :room_tasks, autosave: true

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :require_login

  private

  # This will be required when people sign in
  def require_login
    if ((current_user == nil) || (current_user.role_id == Role.find_by(name: 'inactive').id))
      logger.debug current_user
      flash[:notice] = "You must be logged in! Or, you have not been authorized!"
      redirect_to login_path # redirect to login page
    end
  end

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_filter :require_login

  # request password reset.
  # you get here when the user entered his email in the reset password form and submitted it.
  def create
    @user = User.find_by_email(params[:email])

    # This line sends an email to the user with instructions on how to reset their password (a url with a random token)
    @user.deliver_reset_password_instructions! if @user

    # Tell the user instructions have been sent whether or not email was found.
    # This is to not leak information to attackers about which emails exist in the system.
    redirect_to(root_path, :notice => 'Instructions have been sent to your email.')
  end

  # This is the reset password form.
  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end
  end

  # This action fires when the user has sent the reset password form.
  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end

    # the next line makes the password confirmation validation work
    @user.password_confirmation = params[:user][:password_confirmation]
    # the next line clears the temporary token and updates the password
    if @user.change_password!(params[:user][:password])
      redirect_to(root_path, :notice => 'Password was successfully updated.')
    else
      render :action => "edit"
    end
  end
end

app/controllers/room_tasks_controller.rb
class RoomTasksController < ApplicationController


  def index

  end

  def new
    @roomtask = RoomTask.new()
  end

  def edit

    @roomtask = RoomTask.find(params[:id])

  end

  def update

    # get the account
    @roomtask = RoomTask.find(params[:id])
    # logger.debug params[:id]

    @roomtask.end_date = Time.now

    # update the account
    if @roomtask.update_attributes(roomtask_params())
      # if it updates

      @roomtask = RoomTask.new()

      # render  :edit
      redirect_to new_room_task_path(@roomtask)
    else
      # if it does not update
      # send them back to the edit screen
      render  :edit
    end

  end

  def destroy


  end

  def create

    @roomtask = RoomTask.new(roomtask_params())

    @roomtask.user = current_user

    @roomtask.start_date = Time.now

    if @roomtask.save
      redirect_to edit_room_task_path(id: @roomtask.id)
    else
      render  :new
    end

  end

  private

    def roomtask_params
      params.require(:room_task).permit(:room_id, :task_id, :start_date, :end_date, :note)
    end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  skip_before_action :require_login, except: [:index, :destroy]

  def new

    @user = User.new

  end

  def create

    if @user = login(params[:email], params[:password])

      redirect_back_or_to(new_room_task_path, notice: 'Login successful')

    else

      flash.now[:notice] = 'Login failed'
      render action: 'new'

    end
  end

  def destroy
    logout
    redirect_to(new_room_task_path, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :require_login, only: [:new, :create]
  # before_action :set_user, only: [:show, :edit, :update, :destroy]
  # skip_before_action :require_login, except: [:destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    set_user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    set_user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    @user.role_id = Role.find_by(name: 'inactive').id

      if @user.save

        # auto_login(@user)

        go_new_task()

        # format.html { redirect_to(:users, notice: 'Welcome ' + @user.email ) }
      # format.html { redirect_to @user, notice: 'User was successfully created.' }
      # format.json { render :show, status: :created, location: @user }
      else
        respond_to do |format|
          format.html { render :new }
        end
        # format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    # end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update

    # @user = User.find(params[:id])
    set_user()

    if @user.update(user_params)

      go_new_task()

      # format.html { redirect_to @user, notice: 'User was successfully updated.' }
      # format.json { render :show, status: :ok, location: @user }
    else
      respond_to do |format|
        format.html { render :edit }
      # format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy

    set_user

    @user.role_id = Role.find_by(name: 'inactive').id

    @user.save

    # @user = User.find(params[:id])
    # @user.destroy
    # respond_to do |format|
    #   format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    #   # format.json { head :no_content }
    # end
  end

  def role

    # '/users/role/'

    logger.debug params.inspect

    set_user

    @user.role_id = params[:role_id]

    if(@user.save)

      # return the json response
      render :json => {:success=>true, :status => 201, :message => "Success!" , :other => "role" }

    else

      # return the json response
      render :json => {errors: message}, :status => 401

    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def go_new_task

      @roomtask = RoomTask.new()

      # render  :edit
      redirect_to new_room_task_path(@roomtask)

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :role_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/room_tasks_helper.rb
module RoomTasksHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calltracker</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script> -->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <header>
      <nav class="navbar navbar-default">
        <p id="notice"><%= flash[:notice] %></p>
        <div class="container-fluid">

          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menuCollapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Task Tracker</a>
          </div>

          <div class="collapse navbar-collapse" id="menuCollapse">
            <ul class="nav navbar-nav login-in-nav">
              <% if (current_user) && (current_user.role_id != Role.find_by(name: 'inactive').id) %>
                <li> <%= link_to "Edit Profile", edit_user_path(current_user.id) %> </li>
                <li> <%= link_to "Logout", :logout, method: :post %> </li>
                <% if (current_user) && (current_user.role_id == Role.find_by(name: 'admin').id) %>
                  <li> <%= link_to "Admin", users_path %> </li>
                <% end %>
              <% else %>
                <li> <%= link_to "Register", new_user_path %></li>
                <li> <%= link_to "Login", :login %></li>
              <% end %>
            </ul>
          </div>

        </div>

      </nav>
    </header>
    <div class="row work_div">
      <div class="col-md-12">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/password_resets/edit.html.erb
<h1>Choose a new password</h1>
<%= form_for @user, :url => password_reset_path(@token), :html => {:method => :put} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= @user.email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/room_tasks/_form.html.erb
<%= form_for(@roomtask) do |f| %>
  <% if @roomtask.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@roomtask.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @roomtask.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if(f.object.start_date) %>
    <div class="field">
      <%= f.label "Start" %><br>
      <label for=""><%= f.object.start_date.in_time_zone('Eastern Time (US & Canada)').strftime('%a %b-%d-%Y %H:%M:%S') %></label>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room_id %><br>
    <%= f.collection_select(:room_id, Room.all, :id, :number, {:include_blank => false}, {:class => 'control'})  %>
  </div>

  <div class="field">
    <%= f.label :task_id %><br>
    <%= f.collection_select(:task_id, Task.all, :id, :name, {:include_blank => false}, {:class => 'control'})  %>
  </div>

  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note , class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/room_tasks/edit.html.erb
<h1>End Task</h1>

<%= render 'form' %>

app/views/room_tasks/index.html.erb
<h1>RoomTasks#index</h1>
<p>Find me in app/views/room_tasks/index.html.erb</p>

app/views/room_tasks/new.html.erb
<h1>Start Task</h1>

<%= render 'form' %>

app/views/user_sessions/_forgot_password_form.html.erb
<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %> <%= submit_tag "Reset my password!" %>
  </div>
<% end %>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email  , "", class: 'form-control' %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password , "", class: 'form-control' %>
  </div>
  <div class="actions">
    <%= submit_tag "Login", {:class => 'btn btn-success'} %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path, {:class => 'btn btn-success link_white'} %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email , class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name , class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name , class: 'form-control' %>
  </div>

  <div class="field">
     <%= f.label :password %><br />
     <%= f.password_field :password , class: 'form-control' %>
  </div>
  <div class="field">
     <%= f.label :password_confirmation %><br />
     <%= f.password_field :password_confirmation  , class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Back', new_room_task_path , {:class => 'btn btn-success'} %>

app/views/users/index.html.erb
  <h1>Roles</h1>

  <div id='response' class="response col-md-12">

  </div>

  <% @users.each do |user| %>
    <div id='user_list' class="menu">
      <section id="usersignin" class="col-md-12">
        <h4><%= user.first_name %> <%= user.last_name %></h4>
        <p><%= user.email %></p>
        <%= select_tag(:roles, options_from_collection_for_select(Role.all, 'id','name',user.role_id).html_safe, multiple: false, class: 'role_select control', id: user.id.to_s) %>
      </section>
    </div>
    </br>
  <% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', new_room_task_path , {:class => 'btn btn-success'} %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) , {:class => 'btn btn-success'}
<%= link_to 'Back', new_room_task_path , {:class => 'btn btn-success'} %>